config/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

myapp/urls.py
from django.urls import path

from .views import question, home, result_list, users_upload

urlpatterns = [
    path('', home, name='home'),
    path('quiz/<slug:slug>/', question, name='question'),
    path('result/', result_list, name='result_list'),
    path('users/', users_upload, name='users_upload'),
]

myapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Topic(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    name = models.TextField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Answer(models.Model):
    name = models.CharField(max_length=255)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_right = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Result(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_question = models.IntegerField()
    correct = models.IntegerField()


    @property
    def wrong(self):
        return self.total_question - self.correct

    @property
    def total(self):
        return (self.correct / self.total_question) * 100

myapp/views.py
from random import shuffle
import csv
import io

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Question, Result, Topic, Answer

def home(request):
    topics = Topic.objects.all()
    context = {
        'topics':topics,
    }
    return render(request, 'home.html', context)

@login_required(login_url='login')
def question(request, slug):
    quiz = Topic.objects.get(slug=slug)
    questions = Question.objects.filter(topic = quiz)
    answers = Answer.objects.filter(question__in=questions)
    answers = list(answers)
    questions = list(questions)
    shuffle(answers)
    shuffle(questions)
    if request.method == 'POST':
        correct = 0
        wrong = 0
        for q in questions:
            if request.POST.get(q.name) == "True":
                correct += 1
            else:
                wrong += 1
        Result.objects.create(
            user=User.objects.get(username=request.user.username),
            total_question=len(questions),
            correct=correct,
            topic=quiz,
        )
        context = {
            'questions': questions,
            'answers': answers,
            'correct': correct,
            'wrong': wrong,
            'total_question': len(questions),
            'user': request.user.username,
            'total': round(correct*100/len(questions), 2),
        }
        return render(request, 'result.html',context)
    context = {
        'questions': questions,
        'answers': answers,
    }
    return render(request, 'question.html', context)

def result_list(request):
    results = Result.objects.all()
    context = {
        'results':results,
    }
    return render(request, 'result_list.html', context)

def users_upload(request):
    users = User.objects.all()
    if request.method == "POST":
        csv_file = request.FILES['users']
        file_data = csv_file.read().decode("utf-8")
        io_string = io.StringIO(file_data)
        next(io_string)
        for row in csv.reader(io_string, delimiter=','):
            User.objects.create_user(first_name=row[0], last_name=row[1],
                                     username=row[2], password=row[3],
                                     email=row[4])

    return render(request, 'users_upload.html', {'users':users})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Testlar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'result_list' %}">Natija</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users_upload' %}">{{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Chiqish</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Kirish</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% block content %}

{% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <h1>Testlar</h1><br>
    {% for topic in topics %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ topic.name }}</h5>
                <p class="card-text">Jami savollar soni: {{ topic.question_set.count }}</p>
                <a href="{% url 'question' topic.slug %}" class="btn btn-primary">Testni boshlash</a>
            </div>
        </div><br>
    {% endfor %}
{% endblock %}

templates/question.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %} {% endblock %}

{% block content %}
    <h1>Testlar</h1>
    <form method="post">
        {% csrf_token %}
        {% if questions %}
            {% for question in questions %}
                {{ question.name }}<br>
                {% for answer in answers %}
                    {% if question.id == answer.question.id %}
                        <input type="radio" name="{{ question.name }}" value="{{ answer.is_right }}">
                        <label>{{ answer.name }}</label><br>
                    {% endif %}
                {% endfor %}
                <hr>
            {% endfor %}<br>
            <button class="btn btn-success" type="submit">
                Yakunlash
            </button>
        {% else %}
            <p>Savollar mavjud emas!</p>
        {% endif %}
    </form>
{% endblock %}

templates/result.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% load widget_tweaks %}

{% block content %}
    <table class="table caption-top">
  <caption>Natijalar</caption>
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Foydalanuvchi</th>
      <th scope="col">Umumiy savollar soni</th>
      <th scope="col">To'g'ri javoblar soni</th>
      <th scope="col">Noto'g'ri javoblar soni</th>
      <th scope="col">Umumiy ball</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>{{ user }}</td>
      <td>{{ total_question }}</td>
      <td>{{ correct }}</td>
      <td>{{ wrong }}</td>
      <td>{{ total }}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

templates/result_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <h1>Natijalar Ruyxati</h1>
    <hr>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Ism Familiya</th>
            <th scope="col">Mavzu</th>
            <th scope="col">Umumiy savol</th>
            <th scope="col">To'g'ri Javob</th>
            <th scope="col">Ball</th>
            <th scope="col">Sana</th>
        </tr>
        </thead>
        <tbody>
        {% for r in results %}
            <tr>
                <td>{{ r.user.username }}</td>
                <td>{{ r.topic.name }}</td>
                <td>{{ r.total_question }}</td>
                <td>{{ r.correct }}</td>
                <td>{{ r.total }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/users_upload.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
 <h1>Foydalanuvchi qo'shish</h1>
    <hr>
<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <input type="file" name="users" class="form-control">
    </div>
    <button class="btn btn-success">Saqlash</button>
</form>

    <table class="table">
  <thead>
    <tr>
      <th scope="col">T/R</th>
      <th scope="col">Ism</th>
      <th scope="col">Familiya</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
  {% for user in users %}
    <tr>
      <th scope="row">{{ user.id }}</th>
      <td>{{ user.first_name }}</td>
      <td>{{ user.last_name }}</td>
      <td>{{ user.email }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}